### ISSUE TITLE
Variant filters

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#723]
We need to review the filtering feature. Using this analysis saved in Mosaic (https://mosaic.chpc.utah.edu/#/projects/191/analyses), I created a filter with max pop AF of 0.001. I got a bunch of variants and selected one to get this:

<img width="1680" alt="Screen Shot 2021-03-07 at 4 46 01 PM" src="https://user-images.githubusercontent.com/523111/110256055-ca27df80-7f64-11eb-960f-dca91e3db5df.png">

The max pop AF is 53%, so clearly the filter isn't working.

**Comment by AlistairNWard** [comment]
* The badge showing number of variants passing filter is too small for 3 digits. Should be dynamic
* Two links to gnomAD go to different references

**Comment by tonydisera** [comment]
This is caused because of the change I made to only get gnomAD genomes on-demand to speed up response time.  The problem is that some variants don't appear in gnomAD exomes (the default af that VEP uses), but do appear in gnomAD genomes.  So during 'analyze all', since VEP is only looking at exomes, some variants would show as 0% AF because they are not present in the gnomAD exomes.  Then when you click on the variant, the app will annotate the variant 'on-demand' with gnomAD genomes.  

So this is a case where the filter work off of incomplete gnomAD allele frequencies. For the sake of correctness, I think we should take the performance hit and annotate with gnomAD genomes during 'analyze all' rather than 'on-demand'.  

There is a global variable that I will switch to true:
`this.gnomADExtraAll       = true;`

**Comment by AlistairNWard** [comment]
We can discuss whether we need to look at this pre paper release. The filter just has popmax AF, but we show genomes and exomes. There are instances where these have very different values, e.g. below. I filtered on 0.001, so the variant passes based on genomes, but not exomes. It's unclear when setting the filter which is being filtered against.

![Screen Shot 2021-08-04 at 12 42 27 PM](https://user-images.githubusercontent.com/523111/128220736-63641960-22e2-4228-9536-5b429c6dc55e.png)

**Comment by AlistairNWard** [comment]
Just include gnomad genomes in text field

**Comment by AlistairNWard** [comment]
I think this is fixed? @tonydisera

**Comment by AlistairNWard** [comment]
@tonydisera Can you confirm?

**Comment by tonydisera** [comment]
With the rework of annotateVariants in the backend, which now uses Slivar, we are annotating with gnomAD genomes. The filtering is based on this allele frequency.  The AF filtering appears to be working as expected.
