### ISSUE TITLE
Feature request: searching/sorting by significance

### ISSUE THREAD

**Issue by geckomancer** [iobio/gene.iobio#830]
As of now, search can only be initiated by gene name/list or phenotype. If possible and practical to implement, I would appreciate a search feature that would pull up significant variants (i.e. anything that would show up under the “Variants” tab for being: pathogenic in ClinVar, autosomal dominant, recessive, de novo, compound hets, X-linked recessive, or high/moderate impact) without users having to first input a gene name or phenotype.

**Comment by AlistairNWard** [comment]
Thanks for the comment. Unfortunately, this is not possible for gene.iobio to perform. Once provided with a gene list, gene.iobio annotates every gene and then prioritizes variants based on these annotations. Given a list of 100 genes, it can take several minutes to annotate all the variants. In order to determine information on all variants, we would need to annotate all the variants in the vcf file which could take hours and is beyond the capacity of a web app to perform

**Comment by AlistairNWard** [comment]
There are other solutions that we are working on that might address this need though. If you'd like to discuss, shoot me an email at AlistairNWard@gmail.com
