### ISSUE TITLE
Variant annotations

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#846]
**3.2.3. Provide comprehensive variant annotations**
- We will update gene.iobio to read the VCF file header, and extract the names and descriptions of annotations described in the "##INFO”, and “##FORMAT” lines. We will add a modal that will allow the user to select which variant or genotype level annotations should be read and displayed in a new custom annotation panel (Figure 1C).
- We will provide a new mode where only annotations from the VCF file (or Mosaic) will be displayed. This mode will deactivate real-time analysis, and provide extremely fast access to the stored data. This would be an attractive option for newly created VCF files, as the annotations in the file will be up-to-date, but would potentially exclude important annotations if not present in the file. At later time points, or when viewing legacy data, switching to the real-time analysis mode would provide up-to-date information, and contrast these with out-of-date information extracted from the VCF file. (This has been separated out into a new issue #981)
- We will update the Mosaic API to allow gene.iobio to access Mosaic annotations and visualize them. When gene.iobio is launched from Mosaic (Figure 2), users will be able to choose to launch in “local annotations mode”, or choose annotations to load into gene.iobio.

![Asset 12](https://user-images.githubusercontent.com/523111/182192305-338c048f-e9aa-4da2-a120-2c2bba8e8a56.png)

**Comment by tonydisera** [comment]
<img width="1148" alt="Screenshot 2023-08-22 at 11 09 12 AM" src="https://github.com/iobio/gene.iobio/assets/8420103/b55fc1db-b9f9-4033-b42c-1d5bb6fc920d">

**Comment by tonydisera** [comment]
Hi @YangQi007. There are a number of user interface refinements that are needed. Please follow Al's mockup. Here are screen captures with comments on what needs to be fixed in the user interface.
<img width="1001" alt="Screenshot 2023-09-21 at 3 56 11 PM" src="https://github.com/iobio/gene.iobio/assets/8420103/a2ea41e5-58b6-4e82-ab1b-d3f4f7398943">
<img width="654" alt="Screenshot 2023-09-21 at 3 34 12 PM" src="https://github.com/iobio/gene.iobio/assets/8420103/00c3e3a1-bbd9-44f2-8688-154b4e26c166">
<img width="329" alt="Screenshot 2023-09-21 at 3 34 07 PM" src="https://github.com/iobio/gene.iobio/assets/8420103/70800e63-ba88-4e45-86a0-31cdafd6607d">

**Comment by AlistairNWard** [comment]
Do you think it makes sense to leave the annotations as they appear in the VCF (e.g. keep AC instead of Allele Count) because of space constraints? If it stays like this, we can have a tooltip that explains that AC = Allele Count and then have an info button next to the Custom Annotations title that would give a full legend?
