### ISSUE TITLE
Genes with no transcripts

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio#964]
People are still getting confused about what is happening when genes have no transcripts. Go to the demo data for gene TRA as an example. Gene.iobio will spin forever on TRA (if you click on it while it's loading RAI1, it will show 4 variants in the count and spin forever - 4 is the number of variants in RAI1). Here are some things I think we should do:
- [ ] The error message says "No Gencode transcripts for TRA. Using Refseq transcripts instead." This implies that results will be forthcoming from Refseq transcripts, but there are no Refseq transcripts either, so nothing gets loaded. If there are no transcripts, can we change the message to something more like "No transcripts are available for TRA and so many annotations cannot be determined"?
- [ ] Gene.iobio spins forever, but it should still be able to display the variants. If there are no transcripts, can we just not run annotation tools that require a transcript, but still show the variants. The impact would be Unknown (grey) for them all and they could still have e.g. gnomAD annotations

**Comment by tonydisera** [comment]
The gene TRA presents an interesting scenario. There is a gene in the RefSeq gff, but no transcripts. So without a transcript, we can't do any of the annotate variants analysis because transcript is required. It would take a significant amount of effort to rework annotate variants to work without a transcript. 

I will fix the bug so that gene doesn't attempt to annotate the variants since there is no transcript. It will fail gracefully with a message that indicates there are no transcripts for this gene.

There is an existing issue to rework the gene model so that genes that are not in RefSeq or Gencode (or genes that don't have transcripts) and better handled in gene.iobio and other iobio apps. #839

**Comment by AlistairNWard** [comment]
Ok. We should include in the message that no variants are being shown because of this. The implication to the user is that there are no variants in the gene, but that isn't necessarily the case - we're just not showing any if there are no transcripts. Longer term, just displaying the variants would be good.

**Comment by AlistairNWard** [comment]
As to the first point, we need to make it as clear as possible that a lack of transcripts is not a bug, but a lack of information that makes gene.iobio unable to annotate the variants. I keep getting lots of messages from people about this message and I have to keep explaining to people what is going on.

**Comment by tonydisera** [comment]
Test with genes: TRA, WAR

**Comment by AlistairNWard** [comment]
@tonydisera How much effort would it be to just skip the annotation step? For example, IGH does have variants that appear in ClinVar so seeing the variants that fall into this region would still be useful without the annotations. I think you said this is a reasonable amount of work, so it might need to be broken out into its own issue for later, but just wondering.

The alternative solutions are to remove these genes from the list (I'm not a big fan of this as people will still complain - just that they can't pick their gene of interest), or suggest other genes. For example there are a million genes in the same region as IGH that do have transcripts.
